import sqlite3
conn = sqlite3.connect('backend/ats_platform.db')
cursor = conn.cursor()
cursor.execute('SELECT name FROM sqlite_master WHERE type="table"')
tables = cursor.fetchall()
print('Tables:', tables)
cursor.execute('SELECT COUNT(*) FROM users')
count = cursor.fetchone()
print('User count:', count)
cursor.execute('SELECT email FROM users WHERE email = "thomas@workcrew.ai"')
user = cursor.fetchone()
print('Admin user:', user)
cursor.execute('SELECT * FROM organization_members WHERE user_id = (SELECT id FROM users WHERE email = "thomas@workcrew.ai")')
member = cursor.fetchone()
print('Admin membership:', member)
conn.close()